Repository SlottySlots/SlottyMedia, pull requests merged in 2024-08, with the labels that each got.

#51 Feat/sign in out
  SlottyMedia.Tests/Viewmodel/auth/SignInFormVmImplTest.cs
  SlottyMedia.sln.DotSettings.user
  SlottyMedia/Backend/Exceptions/auth/UserAlreadySignedInException.cs
  SlottyMedia/Backend/Services/AuthService.cs
  SlottyMedia/Backend/Services/CookieService..cs
  SlottyMedia/Backend/Services/SignupServiceImpl.cs
  SlottyMedia/Backend/Services/UserService.cs
  SlottyMedia/Backend/ViewModel/Interfaces/ISignInFormVm.cs
  SlottyMedia/Backend/ViewModel/SignInFormVmImpl.cs
  SlottyMedia/Backend/ViewModel/SignupFormVmImpl.cs
  SlottyMedia/Components/Layout/MainLayout.razor
  SlottyMedia/Components/Pages/Register.razor
  SlottyMedia/Program.cs
  SlottyMedia/SlottyMedia.csproj
  slottymedia-docs/docs/code/index.md
  slottymedia-docs/docs/code/slottymedia.backend.exceptions.auth.alreadysignedinexception.md
  slottymedia-docs/docs/code/slottymedia.backend.exceptions.auth.useralreadysignedinexception.md
  slottymedia-docs/docs/code/slottymedia.backend.services.signupserviceimpl.md
  slottymedia-docs/docs/code/slottymedia.backend.services.userservice.md
  slottymedia-docs/docs/code/slottymedia.backend.viewmodel.interfaces.isigninformvm.md
  slottymedia-docs/docs/code/slottymedia.backend.viewmodel.signinformvmimpl.md
  slottymedia-docs/docs/code/slottymedia.backend.viewmodel.signupformvmimpl.md
  slottymedia-docs/docs/code/slottymedia.components.layout.mainlayout.md
Labels: bug, help wanted

#82 80-supabase-client-in-services
  SlottyMedia.DatabaseSeeding/Rules.cs
  SlottyMedia.DatabaseSeeding/SlottyMedia.DatabaseSeeding.csproj
  SlottyMedia.Tests/ServiceTests/PostServiceTests.cs
  SlottyMedia.sln.DotSettings.user
  SlottyMedia/Backend/Services/Interfaces/IPostService.cs
  SlottyMedia/Backend/Services/PostService.cs
  SlottyMedia/Backend/ViewModel/HomePageVmImpl.cs
  slottymedia-docs/docs/code/SlottyMedia/slottymedia.backend.services.interfaces.ipostservice.md
  slottymedia-docs/docs/code/SlottyMedia/slottymedia.backend.services.postservice.md
Labels: enhancement

#92 Fix/fix database seeding
  SlottyMedia.DatabaseSeeding/Rules.cs
  SlottyMedia.DatabaseSeeding/Seeding.cs
Labels: bug

#94 93 currently the created at wont be set correctly
  SlottyMedia.Database/Daos/CommentDao.cs
  SlottyMedia.Database/Daos/FollowerUserRelationDao.cs
  SlottyMedia.Database/Daos/ForumDao.cs
  SlottyMedia.Database/Daos/PostsDao.cs
  SlottyMedia.Database/Daos/RoleDao.cs
  SlottyMedia.Database/Daos/UserDao.cs
  SlottyMedia.Database/Daos/UserLikePostRelationDao.cs
  SlottyMedia/Backend/Dtos/CommentDto.cs
  SlottyMedia/Backend/Dtos/ForumDto.cs
  SlottyMedia/Backend/Dtos/PostDto.cs
  SlottyMedia/Backend/Dtos/UserDto.cs
  SlottyMedia/Backend/ViewModel/MainLayoutVmImpl.cs
  SlottyMedia/Backend/ViewModel/ProfilePageVmImpl.cs
  SlottyMedia/Components/Pages/Profile.razor
  slottymedia-docs/docs/code/SlottyMedia.Database/slottymedia.database.daos.commentdao.md
  slottymedia-docs/docs/code/SlottyMedia.Database/slottymedia.database.daos.followeruserrelationdao.md
  slottymedia-docs/docs/code/SlottyMedia.Database/slottymedia.database.daos.forumdao.md
  slottymedia-docs/docs/code/SlottyMedia.Database/slottymedia.database.daos.postsdao.md
  slottymedia-docs/docs/code/SlottyMedia.Database/slottymedia.database.daos.roledao.md
  slottymedia-docs/docs/code/SlottyMedia.Database/slottymedia.database.daos.userdao.md
  slottymedia-docs/docs/code/SlottyMedia.Database/slottymedia.database.daos.userlikepostrelationdao.md
Labels: bug
